language: java
script: "mvn clean verify"

services:
  - docker
  
env:
  global:
    - CACHE_DIR=$HOME/docker
#    - APIM_DOCKER_IMAGE=docker-registry.demo.axway.com/demo/api-manager:7.6.2-01
#    - APIM_DOCKER_IMAGE=docker-registry.demo.axway.com/swagger-promote/api-mgr-with-policies:7.6.2-SP2
    - APIM_DOCKER_IMAGE_7_7=docker-registry.demo.axway.com/swagger-promote/api-mgr-with-policies:7.7
    - CASSANDRA_DOCKER_IMAGE=cassandra:2.2.8
    - CACHE_FILE_APIM_7_7=$CACHE_DIR/api-manager_7_7-01.cache.tar.gz
    - CACHE_FILE_CASSANDRA=$CACHE_DIR/cassandra_2_2_8.cache.tar.gz
    - counter=0
  
cache:
  directories:
    - $CACHE_DIR
    - '$HOME/.m2/repository'

before_install:
  - if [ ! -f $CACHE_FILE_APIM_7_7 ]; then sudo sed 's/DOCKER_OPTS="/DOCKER_OPTS="--insecure-registry=docker-registry.demo.axway.com /g' -i /etc/default/docker; fi
  - if [ ! -f $CACHE_FILE_APIM_7_7 ]; then sudo service docker restart; fi
  #- sudo apt-get update
  #- sudo apt-get install curl
  # All files in this folder will be cached for the next build
  - mkdir -p $CACHE_DIR
  # Login to the Docker-Registry
  - if [ ! -f $CACHE_FILE_APIM_7_7 ]; then docker login --username $AXWAY_DOCKER_REG_USER --password $AXWAY_DOCKER_REG_PASS docker-registry.demo.axway.com; fi
  # Downloading the APIM-Docker-Image takes too long (Timeout 10 minutes) - Externalized to make use of travis_wait
  # In this script, we are either using the cached version or download a new Docker-Image
  - travis_wait build/pull_apim_docker_image.sh
  # Now it's time to safe the downloaded API-Management Docker-Image into the cache folder
  - if [ ! -f $CACHE_FILE_APIM_7_7 ]; then docker save $APIM_DOCKER_IMAGE_7_7 | gzip > $CACHE_FILE_APIM_7_7; fi
  # Pull Cassandra Image or use the cache
  - travis_wait build/pull_cassandra_docker_image.sh
  # Safe Cassandra image inc cache file
  - if [ ! -f $CACHE_FILE_CASSANDRA ]; then docker save $CASSANDRA_DOCKER_IMAGE | gzip > $CACHE_FILE_CASSANDRA; fi

install:
  # Start Cassandra and wait that port 9042 is reachable
  - docker-compose run --rm start_cassandra
  # Start the API-Gateway + API-Manager
  - docker-compose run --rm start_apimgmt
  # Give API-Manager a moment to start
  - docker-compose logs --tail 30 apimgmt
  

  
